name: Test and build the project
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y libgl1-mesa-dev xorg-dev portaudio19-dev
          go get .

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build main.go -o game

